[package]
name = "igpay-atinlay"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.4.5"

[dependencies.is-vowel]
git = "https://github.com/BartMassey/is-vowel"
branch = "main"
